[tool]

[tool.black]
line-length = 100

[tool.isort]
force_single_line = true # Force from .. import to be 1 per line, minimizing changes at time of implementation
lines_after_imports = 2 # Ensures consistency for cases when there's variable vs function/class definitions after imports
lines_between_types = 1 # Separate import/from with 1 line, minimizing changes at time of implementation
no_lines_before = "LOCALFOLDER" # Keeps local imports bundled with first-party
profile = "black" # Avoid conflict with black

[tool.pylint]

[tool.pylint.format]
max-line-length = 100

[tool.pylint.messages_control]
disable = ["fixme"]
enable = [
  "useless-suppression", # Identify unneeded pylint disable statements

]
