name: ansible-lint
on:
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the collection repository
        uses: Qalthos/github_actions/.github/actions/checkout_repository@depends_on
        with:
          repository: ${{ github.repository }}
          path: ${{ env.source_directory }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
