name: Build collections
on:
  workflow_call:

jobs:
  sanity:
    env:
      PY_COLORS: "1"
      source_directory: "./source"
      dependency_directory: "./dependency"
    runs-on: ubuntu-latest

    name: Build collections for later
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Github action python requirements
        run: pip3 install yq
        shell: bash

      - name: Checkout the collection repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.source_directory }}
          fetch-depth: "0"

      - name: Build collection
        id: build
        uses: Qalthos/github_actions/.github/actions/build_collection@dependencies
        with:
          source_path: ${{ env.source_directory }}
          artifact_name: collection

      - name: Checkout ${{ steps.build.outputs.dependency }}
        uses: actions/checkout@v3
        with:
          repository: ansible-collections/${{ steps.build.outputs.dependency }}
          path: ${{ env.dependency_directory }}
          fetch-depth: "0"

      - name: Build ${{ steps.build.outputs.dependency }}
        uses: Qalthos/github_actions/.github/actions/build_collection@dependencies
        with:
          source_path: ${{ env.dependency_directory }}
          artifact_name: dependencies
