name: Unit tests
on:
  workflow_call:

jobs:
  unit:
    env:
      PY_COLORS: "1"
      source_directory: "./source"
      dependency_directory: "./dependency"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible-version:
          - stable-2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          - stable-2.13
          - milestone
          - devel
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        dependency-source:
          - galaxy
          - github

    name: "py${{ matrix.python-version }} / ${{ matrix.ansible-version }} / ${{ matrix.dependency-source }}"
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible-core (${{ matrix.ansible-version }})
        run: python3 -m pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz --disable-pip-version-check

      - name: Install ${{ steps.identify.outputs.dependency }}
        if: matrix.dependency-source == 'github'
        uses: Qalthos/github_actions/install_collection@dependencies
        with:
          install_python_dependencies: true
          source_path: ${{ env.dependency_directory }}
          artifact_name: dependencies

      - name: Install the collection
        id: install
        uses: Qalthos/github_actions/install_collection@dependencies
        with:
          install_python_dependencies: true
          source_path: ${{ env.source_directory }}
          artifact_name: collection

      - name: Copy the galaxy.yml from source to destination, needed for pytest-ansible-units
        run: cp galaxy.yml ${{ steps.identify.outputs.collection_path }}
        shell: bash
        working-directory: ${{ env.source_directory }}

      - name: Print the ansible version
        run: ansible --version

      - name: Install the unit test dependency
        run: python3 -m pip install git+https://github.com/ansible-community/pytest-ansible-units.git

      - name: Print the python dependencies
        run: python3 -m pip list

      - name: Run unit tests
        run: python -m pytest -vv tests/unit --showlocals
        working-directory: ${{ steps.install.outputs.collection_path }}
